/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PgButton {
        "buttonText": string;
        "buttonType": 'success' | 'danger';
    }
    interface PgInput {
        "inputId": string;
        "label": string;
        "type": string;
    }
    interface PgLogin {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPgButtonElement extends Components.PgButton, HTMLStencilElement {
    }
    var HTMLPgButtonElement: {
        prototype: HTMLPgButtonElement;
        new (): HTMLPgButtonElement;
    };
    interface HTMLPgInputElement extends Components.PgInput, HTMLStencilElement {
    }
    var HTMLPgInputElement: {
        prototype: HTMLPgInputElement;
        new (): HTMLPgInputElement;
    };
    interface HTMLPgLoginElement extends Components.PgLogin, HTMLStencilElement {
    }
    var HTMLPgLoginElement: {
        prototype: HTMLPgLoginElement;
        new (): HTMLPgLoginElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pg-button": HTMLPgButtonElement;
        "pg-input": HTMLPgInputElement;
        "pg-login": HTMLPgLoginElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PgButton {
        "buttonText"?: string;
        "buttonType"?: 'success' | 'danger';
    }
    interface PgInput {
        "inputId"?: string;
        "label"?: string;
        "type"?: string;
    }
    interface PgLogin {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pg-button": PgButton;
        "pg-input": PgInput;
        "pg-login": PgLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pg-button": LocalJSX.PgButton & JSXBase.HTMLAttributes<HTMLPgButtonElement>;
            "pg-input": LocalJSX.PgInput & JSXBase.HTMLAttributes<HTMLPgInputElement>;
            "pg-login": LocalJSX.PgLogin & JSXBase.HTMLAttributes<HTMLPgLoginElement>;
        }
    }
}
